# Generated by Django 5.1.4 on 2024-12-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='serial_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
